### ISSUE TITLE
Crear relaciónes en models.

### ISSUE THREAD

**Issue by ampmangu** [GDGMalaga/GDGWeb#2]
Viendo el models, temporal claro está, que tenemos por ahora, mi intención sería crear las siguientes relaciones:
Un grupo puede tener varios cursos.
Un usuario puede pertenecer a varios grupos. 

Como no quiero liarla por ahora con el models, lo podemos hablar en persona, skype o whatever.

**Comment by angajime** [comment]
Sugiero que no se utilice un [Usuario](https://github.com/GDGMalaga/GDGWeb/blob/master/www/models.py) propio sino que se utilice la clase [django.contrib.auth.models.User](https://docs.djangoproject.com/en/1.8/topics/auth/default/#user-objects) que Django proporciona.

**Comment by baenans** [comment]
Concedida e.e
La idea es usar django-allauth con Google como provider ;).

**Comment by ampmangu** [comment]
Este issue continuará en https://github.com/GDGMalaga/GDGWeb/issues/4
