### ISSUE TITLE
bootstrap-support

### ISSUE THREAD

**Issue by angajime** [GDGMalaga/GDGWeb#7]
I'm doing a little remodeling on my own. This is on-going work. I will pull-request it when its ready.

This is the branch: [bootstrap-support](https://github.com/GDGMalaga/GDGWeb/tree/bootstrap-support)

**Comment by ampmangu** [comment]
I like it. Fix the thing I told you via Gmail and I think we can merge.

**Comment by angajime** [comment]
Fixed on [PR#8](https://github.com/GDGMalaga/GDGWeb/pull/8).

**Comment by angajime** [comment]
Added simple user support for testing and design purposes on [PR#10](https://github.com/GDGMalaga/GDGWeb/pull/10)

**Comment by angajime** [comment]
As [PR#8](https://github.com/GDGMalaga/GDGWeb/pull/8) is now accepted, this issue is closed.

**Comment by angajime** [comment]
As [PR#8](https://github.com/GDGMalaga/GDGWeb/pull/8) is now accepted, this issue is closed.
